spring:
    thymeleaf:
        mode: HTML
    profiles:
        active: dev
    mvc:
        static-path-pattern: /**


mybatis:
    type-aliases-package: com.example.myblog.entity
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true

comment.avatar: /images/avatar.png
message.avatar: /images/14.jpg


