spring:
    thymeleaf:
        mode: HTML
    profiles:
        active: dev

mybatis:
    type-aliases-package: com.example.myblog.entity
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
